### PR TITLE
fluct Bid Adapter: updates for Prebid 5.0

### PR DESCRIPTION
**Pull request by toshi17**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [x] Other

## Description of change

- restore fluctBidAdapter.js compatible for Prebid 5.0
- add support for meta.advertiserDomains

## Other information

- ticket: https://vg-ceg.backlog.com/view/FLUCT_SSP-14436#comment-92750381

### CODE REVIEW

**Comment by toshi17** [comment]
実際の変更部分はここだけ
https://github.com/voyagegroup/Prebid.js/pull/2/commits/b5265dd84af821de11e11dfd4763d9b3fffb3309

**Comment by tomill** [comment]
@toshi17 #3 merge 後、このコマンドの結果を貼ってもらえますか

```
gulp -LLLL test --file test/spec/modules/fluctBidAdapter_spec.js
```

**Comment by toshi17** [comment]
@tomill こんな感じです〜

```bash
~/Workspace/Prebid.js
❯ gulp -LLLL test --file test/spec/modules/fluctBidAdapter_spec.js                                                                                                                                                                    [fluct-support-adomain]

[18:57:09] Using gulpfile ~/Workspace/Prebid.js/gulpfile.js
[18:57:09] Starting 'test'...
[18:57:09] Starting 'clean'...
[18:57:09] Finished 'clean' after 95 ms
[18:57:09] Starting 'lint'...
[18:57:31] Finished 'lint' after 22 s
[18:57:31] Starting 'test'...
17 08 2021 18:57:31.595:WARN [karma-server]: Passing raw CLI options to `new Server(config, done)` is deprecated. Use `parseConfig(configFilePath, cliOptions, {promiseConfig: true, throwErrors: true})` to prepare a processed `Config` instance and pass that as the `config` argument instead.

START:
⚠ ｢wdm｣:
ℹ ｢wdm｣: Compiled with warnings.
ℹ ｢wdm｣: Compiling...
ℹ ｢wdm｣: wait until bundle finished: noop
⚠ ｢wdm｣:
ℹ ｢wdm｣: Compiled with warnings.
17 08 2021 18:57:34.113:INFO [karma-server]: Karma v6.3.4 server started at http://localhost:9876/
17 08 2021 18:57:34.114:INFO [launcher]: Launching browsers ChromeHeadless with concurrency 5
17 08 2021 18:57:34.137:INFO [launcher]: Starting browser ChromeHeadless
17 08 2021 18:57:34.643:INFO [Chrome Headless 92.0.4515.131 (Mac OS 10.15.7)]: Connected on socket sUSukXmYBO4AAVhOAAAB with id 51701851

Finished in 0.009 secs / 0.003 secs @ 18:57:34 GMT+0900 (日本標準時)

SUMMARY:
✔ 10 tests completed
[18:57:34] Finished 'test' after 3.26 s
[18:57:34] Finished 'test' after 25 s
```

**Review by tomill — APPROVED** [review]
lgtm

**Comment by toshi17** [comment]
mm

**Comment by toshi17** [comment]
PR: https://github.com/prebid/Prebid.js/pull/7335

**Pull request closed without merging**
