### PR TITLE
Fluct user syncs

### PR DESCRIPTION
**Pull request by yowcow**
## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- Add `getUserSyncs()` to fluct bid adapter

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by yowcow** [comment]
```
❯ npx gulp test

...

Finished in 27.447 secs / 15.758 secs @ 19:15:44 GMT+0900 (Japan Standard Time)

SUMMARY:
✔ 12307 tests completed
ℹ 12 tests skipped
[19:15:44] Finished 'test-only' after 1.68 min
[19:15:44] Finished 'test' after 4.35 min
```

**Comment by SRkuma** [comment]
そういえばhello_world.htmlが404なんですがyowcowさんはどこのファイルを見てるんです？
https://github.com/integrationExamples/gpt/hello_world.html

**Review by SRkuma — APPROVED** [review]
LGTM

**Comment by SRkuma** [comment]
📝 PRテンプレートに書いてあるpathが間違ってた
https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/hello_world.html

**Comment by yowcow** [comment]
:bow:

**Pull request closed without merging**
